# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import account_post_pb2 as account__post__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in account_post_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountPostsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/AccountPosts/Create',
                request_serializer=account__post__pb2.AccountPostCreateRequest.SerializeToString,
                response_deserializer=account__post__pb2.AccountPostResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/AccountPosts/Update',
                request_serializer=account__post__pb2.AccountPostUpdateRequest.SerializeToString,
                response_deserializer=account__post__pb2.AccountPostResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/AccountPosts/List',
                request_serializer=account__post__pb2.AccountPostListRequest.SerializeToString,
                response_deserializer=account__post__pb2.AccountPostListResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/AccountPosts/Get',
                request_serializer=account__post__pb2.AccountPostGetRequest.SerializeToString,
                response_deserializer=account__post__pb2.AccountPostResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/AccountPosts/Delete',
                request_serializer=account__post__pb2.AccountPostGetRequest.SerializeToString,
                response_deserializer=account__post__pb2.AccountPostResponse.FromString,
                _registered_method=True)


class AccountPostsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Create creates a new post
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Update updates a specified post
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """List fetches all/selected number of posts from a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Get fetches a specified post
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete deletes a specified post
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountPostsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=account__post__pb2.AccountPostCreateRequest.FromString,
                    response_serializer=account__post__pb2.AccountPostResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=account__post__pb2.AccountPostUpdateRequest.FromString,
                    response_serializer=account__post__pb2.AccountPostResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=account__post__pb2.AccountPostListRequest.FromString,
                    response_serializer=account__post__pb2.AccountPostListResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=account__post__pb2.AccountPostGetRequest.FromString,
                    response_serializer=account__post__pb2.AccountPostResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=account__post__pb2.AccountPostGetRequest.FromString,
                    response_serializer=account__post__pb2.AccountPostResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AccountPosts', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AccountPosts', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountPosts(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AccountPosts/Create',
            account__post__pb2.AccountPostCreateRequest.SerializeToString,
            account__post__pb2.AccountPostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AccountPosts/Update',
            account__post__pb2.AccountPostUpdateRequest.SerializeToString,
            account__post__pb2.AccountPostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AccountPosts/List',
            account__post__pb2.AccountPostListRequest.SerializeToString,
            account__post__pb2.AccountPostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AccountPosts/Get',
            account__post__pb2.AccountPostGetRequest.SerializeToString,
            account__post__pb2.AccountPostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AccountPosts/Delete',
            account__post__pb2.AccountPostGetRequest.SerializeToString,
            account__post__pb2.AccountPostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
