# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authentication.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'authentication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61uthentication.proto\"\xc1\x01\n\x13RegistrationRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x0b\n\x03\x64ob\x18\x05 \x01(\t\x12\x0e\n\x06gender\x18\x06 \x01(\t\x12\x0e\n\x06\x64\x65gree\x18\x07 \x01(\t\x12\x15\n\ryear_of_study\x18\x08 \x01(\t\x12\x11\n\tgrad_year\x18\t \x01(\t\x12\x0b\n\x03tag\x18\n \x03(\t\"f\n\x16\x41uthenticationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"/\n\x10\x45mailAuthRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04skip\x18\x02 \x01(\x08\"4\n\rEmailAuthSent\x12\x0c\n\x04sent\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x03(\t\"*\n\x0f\x45mailAuthVerify\x12\x0b\n\x03otp\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\"@\n\x15\x45mailVerifiedResponse\x12\x10\n\x08verified\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x03(\t2\x89\x02\n\x0e\x41uthentication\x12?\n\x0cRegisterUser\x12\x14.RegistrationRequest\x1a\x17.AuthenticationResponse\"\x00\x12\x35\n\tLoginUser\x12\r.LoginRequest\x1a\x17.AuthenticationResponse\"\x00\x12\x37\n\x10SendEmailRequest\x12\x11.EmailAuthRequest\x1a\x0e.EmailAuthSent\"\x00\x12\x46\n\x18\x45mailConfirmationRequest\x12\x10.EmailAuthVerify\x1a\x16.EmailVerifiedResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authentication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTRATIONREQUEST']._serialized_start=25
  _globals['_REGISTRATIONREQUEST']._serialized_end=218
  _globals['_AUTHENTICATIONRESPONSE']._serialized_start=220
  _globals['_AUTHENTICATIONRESPONSE']._serialized_end=322
  _globals['_LOGINREQUEST']._serialized_start=324
  _globals['_LOGINREQUEST']._serialized_end=371
  _globals['_EMAILAUTHREQUEST']._serialized_start=373
  _globals['_EMAILAUTHREQUEST']._serialized_end=420
  _globals['_EMAILAUTHSENT']._serialized_start=422
  _globals['_EMAILAUTHSENT']._serialized_end=474
  _globals['_EMAILAUTHVERIFY']._serialized_start=476
  _globals['_EMAILAUTHVERIFY']._serialized_end=518
  _globals['_EMAILVERIFIEDRESPONSE']._serialized_start=520
  _globals['_EMAILVERIFIEDRESPONSE']._serialized_end=584
  _globals['_AUTHENTICATION']._serialized_start=587
  _globals['_AUTHENTICATION']._serialized_end=852
# @@protoc_insertion_point(module_scope)
