# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import authentication_pb2 as authentication__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in authentication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthenticationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/Authentication/RegisterUser',
                request_serializer=authentication__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=authentication__pb2.AuthenticationResponse.FromString,
                _registered_method=True)
        self.LoginUser = channel.unary_unary(
                '/Authentication/LoginUser',
                request_serializer=authentication__pb2.LoginRequest.SerializeToString,
                response_deserializer=authentication__pb2.AuthenticationResponse.FromString,
                _registered_method=True)
        self.SendEmailRequest = channel.unary_unary(
                '/Authentication/SendEmailRequest',
                request_serializer=authentication__pb2.EmailAuthRequest.SerializeToString,
                response_deserializer=authentication__pb2.EmailAuthSent.FromString,
                _registered_method=True)
        self.EmailConfirmationRequest = channel.unary_unary(
                '/Authentication/EmailConfirmationRequest',
                request_serializer=authentication__pb2.EmailAuthVerify.SerializeToString,
                response_deserializer=authentication__pb2.EmailVerifiedResponse.FromString,
                _registered_method=True)


class AuthenticationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterUser(self, request, context):
        """RegisterUser registers a user with the provided data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginUser(self, request, context):
        """LoginUser logs in a user with the provided data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEmailRequest(self, request, context):
        """SendEmailRequest sends a request to an email for validation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmailConfirmationRequest(self, request, context):
        """EmailConfirmationRequest sends a request to validate the email with the given code
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=authentication__pb2.RegistrationRequest.FromString,
                    response_serializer=authentication__pb2.AuthenticationResponse.SerializeToString,
            ),
            'LoginUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginUser,
                    request_deserializer=authentication__pb2.LoginRequest.FromString,
                    response_serializer=authentication__pb2.AuthenticationResponse.SerializeToString,
            ),
            'SendEmailRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEmailRequest,
                    request_deserializer=authentication__pb2.EmailAuthRequest.FromString,
                    response_serializer=authentication__pb2.EmailAuthSent.SerializeToString,
            ),
            'EmailConfirmationRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.EmailConfirmationRequest,
                    request_deserializer=authentication__pb2.EmailAuthVerify.FromString,
                    response_serializer=authentication__pb2.EmailVerifiedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Authentication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Authentication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Authentication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Authentication/RegisterUser',
            authentication__pb2.RegistrationRequest.SerializeToString,
            authentication__pb2.AuthenticationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Authentication/LoginUser',
            authentication__pb2.LoginRequest.SerializeToString,
            authentication__pb2.AuthenticationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendEmailRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Authentication/SendEmailRequest',
            authentication__pb2.EmailAuthRequest.SerializeToString,
            authentication__pb2.EmailAuthSent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmailConfirmationRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Authentication/EmailConfirmationRequest',
            authentication__pb2.EmailAuthVerify.SerializeToString,
            authentication__pb2.EmailVerifiedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
