# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: community.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'community.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ommunity.proto\"j\n\x16\x43ommunityCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06public\x18\x03 \x01(\x08\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x0f\n\x07\x64\x65grees\x18\x05 \x03(\t\"v\n\x16\x43ommunityUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06public\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x0f\n\x07\x64\x65grees\x18\x06 \x03(\t\"\"\n\x14\x43ommunityViewRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"$\n\x16\x43ommunityDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"U\n\x16\x42\x61sicCommunityResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t\"^\n\x13\x43ommunityIDResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t\x12\n\n\x02id\x18\x04 \x01(\x05\"u\n\x15\x43ommunityDataResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06public\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x0f\n\x07\x64\x65grees\x18\x06 \x03(\t2\x9f\x02\n\tCommunity\x12\x42\n\x0f\x43ommunityCreate\x12\x17.CommunityCreateRequest\x1a\x14.CommunityIDResponse\"\x00\x12\x45\n\x0f\x43ommunityUpdate\x12\x17.CommunityUpdateRequest\x1a\x17.BasicCommunityResponse\"\x00\x12@\n\rCommunityView\x12\x15.CommunityViewRequest\x1a\x16.CommunityDataResponse\"\x00\x12\x45\n\x0f\x43ommunityDelete\x12\x17.CommunityDeleteRequest\x1a\x17.BasicCommunityResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'community_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMUNITYCREATEREQUEST']._serialized_start=19
  _globals['_COMMUNITYCREATEREQUEST']._serialized_end=125
  _globals['_COMMUNITYUPDATEREQUEST']._serialized_start=127
  _globals['_COMMUNITYUPDATEREQUEST']._serialized_end=245
  _globals['_COMMUNITYVIEWREQUEST']._serialized_start=247
  _globals['_COMMUNITYVIEWREQUEST']._serialized_end=281
  _globals['_COMMUNITYDELETEREQUEST']._serialized_start=283
  _globals['_COMMUNITYDELETEREQUEST']._serialized_end=319
  _globals['_BASICCOMMUNITYRESPONSE']._serialized_start=321
  _globals['_BASICCOMMUNITYRESPONSE']._serialized_end=406
  _globals['_COMMUNITYIDRESPONSE']._serialized_start=408
  _globals['_COMMUNITYIDRESPONSE']._serialized_end=502
  _globals['_COMMUNITYDATARESPONSE']._serialized_start=504
  _globals['_COMMUNITYDATARESPONSE']._serialized_end=621
  _globals['_COMMUNITY']._serialized_start=624
  _globals['_COMMUNITY']._serialized_end=911
# @@protoc_insertion_point(module_scope)
