# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import community_member_management_pb2 as community__member__management__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in community_member_management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemberManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PromoteUser = channel.unary_unary(
                '/MemberManagement/PromoteUser',
                request_serializer=community__member__management__pb2.UserRequest.SerializeToString,
                response_deserializer=community__member__management__pb2.MemberActionResponse.FromString,
                _registered_method=True)
        self.DemoteUser = channel.unary_unary(
                '/MemberManagement/DemoteUser',
                request_serializer=community__member__management__pb2.UserRequest.SerializeToString,
                response_deserializer=community__member__management__pb2.MemberActionResponse.FromString,
                _registered_method=True)
        self.BanUser = channel.unary_unary(
                '/MemberManagement/BanUser',
                request_serializer=community__member__management__pb2.UserRequest.SerializeToString,
                response_deserializer=community__member__management__pb2.MemberActionResponse.FromString,
                _registered_method=True)


class MemberManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PromoteUser(self, request, context):
        """PromoteUser is used for promotion of a specific user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DemoteUser(self, request, context):
        """DemoteUser is used for demoting a specific user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BanUser(self, request, context):
        """BanUser is used by admins to either ban or unban users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemberManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PromoteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteUser,
                    request_deserializer=community__member__management__pb2.UserRequest.FromString,
                    response_serializer=community__member__management__pb2.MemberActionResponse.SerializeToString,
            ),
            'DemoteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DemoteUser,
                    request_deserializer=community__member__management__pb2.UserRequest.FromString,
                    response_serializer=community__member__management__pb2.MemberActionResponse.SerializeToString,
            ),
            'BanUser': grpc.unary_unary_rpc_method_handler(
                    servicer.BanUser,
                    request_deserializer=community__member__management__pb2.UserRequest.FromString,
                    response_serializer=community__member__management__pb2.MemberActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MemberManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MemberManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemberManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PromoteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MemberManagement/PromoteUser',
            community__member__management__pb2.UserRequest.SerializeToString,
            community__member__management__pb2.MemberActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DemoteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MemberManagement/DemoteUser',
            community__member__management__pb2.UserRequest.SerializeToString,
            community__member__management__pb2.MemberActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BanUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MemberManagement/BanUser',
            community__member__management__pb2.UserRequest.SerializeToString,
            community__member__management__pb2.MemberActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
