# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import community_pb2 as community__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in community_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommunityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommunityCreate = channel.unary_unary(
                '/Community/CommunityCreate',
                request_serializer=community__pb2.CommunityCreateRequest.SerializeToString,
                response_deserializer=community__pb2.CommunityIDResponse.FromString,
                _registered_method=True)
        self.CommunityUpdate = channel.unary_unary(
                '/Community/CommunityUpdate',
                request_serializer=community__pb2.CommunityUpdateRequest.SerializeToString,
                response_deserializer=community__pb2.BasicCommunityResponse.FromString,
                _registered_method=True)
        self.CommunityView = channel.unary_unary(
                '/Community/CommunityView',
                request_serializer=community__pb2.CommunityViewRequest.SerializeToString,
                response_deserializer=community__pb2.CommunityDataResponse.FromString,
                _registered_method=True)
        self.CommunityDelete = channel.unary_unary(
                '/Community/CommunityDelete',
                request_serializer=community__pb2.CommunityDeleteRequest.SerializeToString,
                response_deserializer=community__pb2.BasicCommunityResponse.FromString,
                _registered_method=True)


class CommunityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CommunityCreate(self, request, context):
        """CommunityCreate creates a new community
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommunityUpdate(self, request, context):
        """CommunityUpdate updates a specified community
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommunityView(self, request, context):
        """CommunityView fetches a specified community data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommunityDelete(self, request, context):
        """CommunityDelete deletes a specified community
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CommunityCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.CommunityCreate,
                    request_deserializer=community__pb2.CommunityCreateRequest.FromString,
                    response_serializer=community__pb2.CommunityIDResponse.SerializeToString,
            ),
            'CommunityUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.CommunityUpdate,
                    request_deserializer=community__pb2.CommunityUpdateRequest.FromString,
                    response_serializer=community__pb2.BasicCommunityResponse.SerializeToString,
            ),
            'CommunityView': grpc.unary_unary_rpc_method_handler(
                    servicer.CommunityView,
                    request_deserializer=community__pb2.CommunityViewRequest.FromString,
                    response_serializer=community__pb2.CommunityDataResponse.SerializeToString,
            ),
            'CommunityDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.CommunityDelete,
                    request_deserializer=community__pb2.CommunityDeleteRequest.FromString,
                    response_serializer=community__pb2.BasicCommunityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Community', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Community', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Community(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CommunityCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Community/CommunityCreate',
            community__pb2.CommunityCreateRequest.SerializeToString,
            community__pb2.CommunityIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommunityUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Community/CommunityUpdate',
            community__pb2.CommunityUpdateRequest.SerializeToString,
            community__pb2.BasicCommunityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommunityView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Community/CommunityView',
            community__pb2.CommunityViewRequest.SerializeToString,
            community__pb2.CommunityDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommunityDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Community/CommunityDelete',
            community__pb2.CommunityDeleteRequest.SerializeToString,
            community__pb2.BasicCommunityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
