# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import community_announcement_pb2 as community__announcement__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in community_announcement_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommunityAnnouncementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommunityCreateAnnouncement = channel.unary_unary(
                '/CommunityAnnouncement/CommunityCreateAnnouncement',
                request_serializer=community__announcement__pb2.CommunityAnnouncementCreateRequest.SerializeToString,
                response_deserializer=community__announcement__pb2.CommunityAnnouncementResponse.FromString,
                _registered_method=True)
        self.CommunityUpdateAnnouncement = channel.unary_unary(
                '/CommunityAnnouncement/CommunityUpdateAnnouncement',
                request_serializer=community__announcement__pb2.CommunityAnnouncementUpdateRequest.SerializeToString,
                response_deserializer=community__announcement__pb2.CommunityAnnouncementResponse.FromString,
                _registered_method=True)
        self.CommunityViewSelectAnnouncement = channel.unary_unary(
                '/CommunityAnnouncement/CommunityViewSelectAnnouncement',
                request_serializer=community__announcement__pb2.CommunityAnnouncementViewSelectRequest.SerializeToString,
                response_deserializer=community__announcement__pb2.AllCommunityAnnouncementResponse.FromString,
                _registered_method=True)
        self.CommunityDeleteAnnouncement = channel.unary_unary(
                '/CommunityAnnouncement/CommunityDeleteAnnouncement',
                request_serializer=community__announcement__pb2.CommunityAnnouncementDeleteRequest.SerializeToString,
                response_deserializer=community__announcement__pb2.CommunityAnnouncementResponse.FromString,
                _registered_method=True)


class CommunityAnnouncementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CommunityCreateAnnouncement(self, request, context):
        """CommunityCreateAnnouncement creates a new community announcement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommunityUpdateAnnouncement(self, request, context):
        """CommunityUpdateAnnouncement updates a specified community announcement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommunityViewSelectAnnouncement(self, request, context):
        """CommunityViewSelectAnnouncement fetches a specified community number of announcements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommunityDeleteAnnouncement(self, request, context):
        """CommunityDeleteAnnouncement deletes a specified community announcement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunityAnnouncementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CommunityCreateAnnouncement': grpc.unary_unary_rpc_method_handler(
                    servicer.CommunityCreateAnnouncement,
                    request_deserializer=community__announcement__pb2.CommunityAnnouncementCreateRequest.FromString,
                    response_serializer=community__announcement__pb2.CommunityAnnouncementResponse.SerializeToString,
            ),
            'CommunityUpdateAnnouncement': grpc.unary_unary_rpc_method_handler(
                    servicer.CommunityUpdateAnnouncement,
                    request_deserializer=community__announcement__pb2.CommunityAnnouncementUpdateRequest.FromString,
                    response_serializer=community__announcement__pb2.CommunityAnnouncementResponse.SerializeToString,
            ),
            'CommunityViewSelectAnnouncement': grpc.unary_unary_rpc_method_handler(
                    servicer.CommunityViewSelectAnnouncement,
                    request_deserializer=community__announcement__pb2.CommunityAnnouncementViewSelectRequest.FromString,
                    response_serializer=community__announcement__pb2.AllCommunityAnnouncementResponse.SerializeToString,
            ),
            'CommunityDeleteAnnouncement': grpc.unary_unary_rpc_method_handler(
                    servicer.CommunityDeleteAnnouncement,
                    request_deserializer=community__announcement__pb2.CommunityAnnouncementDeleteRequest.FromString,
                    response_serializer=community__announcement__pb2.CommunityAnnouncementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommunityAnnouncement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CommunityAnnouncement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommunityAnnouncement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CommunityCreateAnnouncement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommunityAnnouncement/CommunityCreateAnnouncement',
            community__announcement__pb2.CommunityAnnouncementCreateRequest.SerializeToString,
            community__announcement__pb2.CommunityAnnouncementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommunityUpdateAnnouncement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommunityAnnouncement/CommunityUpdateAnnouncement',
            community__announcement__pb2.CommunityAnnouncementUpdateRequest.SerializeToString,
            community__announcement__pb2.CommunityAnnouncementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommunityViewSelectAnnouncement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommunityAnnouncement/CommunityViewSelectAnnouncement',
            community__announcement__pb2.CommunityAnnouncementViewSelectRequest.SerializeToString,
            community__announcement__pb2.AllCommunityAnnouncementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommunityDeleteAnnouncement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommunityAnnouncement/CommunityDeleteAnnouncement',
            community__announcement__pb2.CommunityAnnouncementDeleteRequest.SerializeToString,
            community__announcement__pb2.CommunityAnnouncementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
