# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: community_joins.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'community_joins.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommunity_joins.proto\"?\n\x16\x43ommunityActionRequest\x12\x14\n\x0c\x63ommunity_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"W\n\x16\x43ommunityInviteRequest\x12\x14\n\x0c\x63ommunity_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x16\n\x0einvite_user_id\x18\x03 \x01(\x05\"V\n\x17\x43ommunityActionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t2\xad\x02\n\x0e\x43ommunityJoins\x12\x44\n\rJoinCommunity\x12\x17.CommunityActionRequest\x1a\x18.CommunityActionResponse\"\x00\x12\x45\n\x0eLeaveCommunity\x12\x17.CommunityActionRequest\x1a\x18.CommunityActionResponse\"\x00\x12\x44\n\rWithCommunity\x12\x17.CommunityActionRequest\x1a\x18.CommunityActionResponse\"\x00\x12H\n\x11InviteToCommunity\x12\x17.CommunityInviteRequest\x1a\x18.CommunityActionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'community_joins_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMUNITYACTIONREQUEST']._serialized_start=25
  _globals['_COMMUNITYACTIONREQUEST']._serialized_end=88
  _globals['_COMMUNITYINVITEREQUEST']._serialized_start=90
  _globals['_COMMUNITYINVITEREQUEST']._serialized_end=177
  _globals['_COMMUNITYACTIONRESPONSE']._serialized_start=179
  _globals['_COMMUNITYACTIONRESPONSE']._serialized_end=265
  _globals['_COMMUNITYJOINS']._serialized_start=268
  _globals['_COMMUNITYJOINS']._serialized_end=569
# @@protoc_insertion_point(module_scope)
