# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_fetching.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'data_fetching.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61ta_fetching.proto\x1a\x1bgoogle/protobuf/empty.proto\"]\n\x10\x44\x61taListResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\t2\x82\x01\n\tDataFetch\x12;\n\x0c\x46\x65tchDegrees\x12\x16.google.protobuf.Empty\x1a\x11.DataListResponse\"\x00\x12\x38\n\tFetchTags\x12\x16.google.protobuf.Empty\x1a\x11.DataListResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_fetching_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATALISTRESPONSE']._serialized_start=52
  _globals['_DATALISTRESPONSE']._serialized_end=145
  _globals['_DATAFETCH']._serialized_start=148
  _globals['_DATAFETCH']._serialized_end=278
# @@protoc_insertion_point(module_scope)
