# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import degree_pb2 as degree__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in degree_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DegreesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/Degrees/Create',
                request_serializer=degree__pb2.DegreeCreateRequest.SerializeToString,
                response_deserializer=degree__pb2.DegreeCreateResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/Degrees/Delete',
                request_serializer=degree__pb2.DegreeDeleteRequest.SerializeToString,
                response_deserializer=degree__pb2.DegreeDeleteResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/Degrees/Get',
                request_serializer=degree__pb2.DegreeGetRequest.SerializeToString,
                response_deserializer=degree__pb2.DegreeGetResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/Degrees/List',
                request_serializer=degree__pb2.DegreeListRequest.SerializeToString,
                response_deserializer=degree__pb2.DegreeListResponse.FromString,
                _registered_method=True)


class DegreesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Create creates a Degree.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete deletes a Degree.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Get by id or name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """List returns all Degrees found, allowing for partial name matching.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DegreesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=degree__pb2.DegreeCreateRequest.FromString,
                    response_serializer=degree__pb2.DegreeCreateResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=degree__pb2.DegreeDeleteRequest.FromString,
                    response_serializer=degree__pb2.DegreeDeleteResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=degree__pb2.DegreeGetRequest.FromString,
                    response_serializer=degree__pb2.DegreeGetResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=degree__pb2.DegreeListRequest.FromString,
                    response_serializer=degree__pb2.DegreeListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Degrees', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Degrees', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Degrees(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Degrees/Create',
            degree__pb2.DegreeCreateRequest.SerializeToString,
            degree__pb2.DegreeCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Degrees/Delete',
            degree__pb2.DegreeDeleteRequest.SerializeToString,
            degree__pb2.DegreeDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Degrees/Get',
            degree__pb2.DegreeGetRequest.SerializeToString,
            degree__pb2.DegreeGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Degrees/List',
            degree__pb2.DegreeListRequest.SerializeToString,
            degree__pb2.DegreeListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
