# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: degree.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'degree.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65gree.proto\"J\n\x06\x44\x65gree\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\x03\x12\x12\n\nupdated_at\x18\x04 \x01(\x03\"#\n\x13\x44\x65greeCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"_\n\x14\x44\x65greeCreateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t\x12\n\n\x02id\x18\x04 \x01(\x03\"!\n\x13\x44\x65greeDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"S\n\x14\x44\x65greeDeleteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t\",\n\x10\x44\x65greeGetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"i\n\x11\x44\x65greeGetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t\x12\x17\n\x06\x64\x65gree\x18\x04 \x01(\x0b\x32\x07.Degree\">\n\x11\x44\x65greeListRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\"k\n\x12\x44\x65greeListResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t\x12\x18\n\x07\x64\x65grees\x18\x04 \x03(\x0b\x32\x07.Degree2\xde\x01\n\x07\x44\x65grees\x12\x37\n\x06\x43reate\x12\x14.DegreeCreateRequest\x1a\x15.DegreeCreateResponse\"\x00\x12\x37\n\x06\x44\x65lete\x12\x14.DegreeDeleteRequest\x1a\x15.DegreeDeleteResponse\"\x00\x12.\n\x03Get\x12\x11.DegreeGetRequest\x1a\x12.DegreeGetResponse\"\x00\x12\x31\n\x04List\x12\x12.DegreeListRequest\x1a\x13.DegreeListResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'degree_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEGREE']._serialized_start=16
  _globals['_DEGREE']._serialized_end=90
  _globals['_DEGREECREATEREQUEST']._serialized_start=92
  _globals['_DEGREECREATEREQUEST']._serialized_end=127
  _globals['_DEGREECREATERESPONSE']._serialized_start=129
  _globals['_DEGREECREATERESPONSE']._serialized_end=224
  _globals['_DEGREEDELETEREQUEST']._serialized_start=226
  _globals['_DEGREEDELETEREQUEST']._serialized_end=259
  _globals['_DEGREEDELETERESPONSE']._serialized_start=261
  _globals['_DEGREEDELETERESPONSE']._serialized_end=344
  _globals['_DEGREEGETREQUEST']._serialized_start=346
  _globals['_DEGREEGETREQUEST']._serialized_end=390
  _globals['_DEGREEGETRESPONSE']._serialized_start=392
  _globals['_DEGREEGETRESPONSE']._serialized_end=497
  _globals['_DEGREELISTREQUEST']._serialized_start=499
  _globals['_DEGREELISTREQUEST']._serialized_end=561
  _globals['_DEGREELISTRESPONSE']._serialized_start=563
  _globals['_DEGREELISTRESPONSE']._serialized_end=670
  _globals['_DEGREES']._serialized_start=673
  _globals['_DEGREES']._serialized_end=895
# @@protoc_insertion_point(module_scope)
