# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tag.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttag.proto\"V\n\x03Tag\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\x03\x12\x12\n\nupdated_at\x18\x04 \x01(\x03\x12\r\n\x05\x63ount\x18\x05 \x01(\x03\",\n\x10TagCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x03\"\\\n\x11TagCreateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t\x12\n\n\x02id\x18\x04 \x01(\x03\"\x1e\n\x10TagDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"P\n\x11TagDeleteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t\")\n\rTagGetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"`\n\x0eTagGetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t\x12\x11\n\x03tag\x18\x04 \x01(\x0b\x32\x04.Tag\";\n\x0eTagListRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\"b\n\x0fTagListResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhttp_status\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x03(\t\x12\x12\n\x04tags\x18\x04 \x03(\x0b\x32\x04.Tag2\xc3\x01\n\x04Tags\x12\x31\n\x06\x43reate\x12\x11.TagCreateRequest\x1a\x12.TagCreateResponse\"\x00\x12\x31\n\x06\x44\x65lete\x12\x11.TagDeleteRequest\x1a\x12.TagDeleteResponse\"\x00\x12(\n\x03Get\x12\x0e.TagGetRequest\x1a\x0f.TagGetResponse\"\x00\x12+\n\x04List\x12\x0f.TagListRequest\x1a\x10.TagListResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAG']._serialized_start=13
  _globals['_TAG']._serialized_end=99
  _globals['_TAGCREATEREQUEST']._serialized_start=101
  _globals['_TAGCREATEREQUEST']._serialized_end=145
  _globals['_TAGCREATERESPONSE']._serialized_start=147
  _globals['_TAGCREATERESPONSE']._serialized_end=239
  _globals['_TAGDELETEREQUEST']._serialized_start=241
  _globals['_TAGDELETEREQUEST']._serialized_end=271
  _globals['_TAGDELETERESPONSE']._serialized_start=273
  _globals['_TAGDELETERESPONSE']._serialized_end=353
  _globals['_TAGGETREQUEST']._serialized_start=355
  _globals['_TAGGETREQUEST']._serialized_end=396
  _globals['_TAGGETRESPONSE']._serialized_start=398
  _globals['_TAGGETRESPONSE']._serialized_end=494
  _globals['_TAGLISTREQUEST']._serialized_start=496
  _globals['_TAGLISTREQUEST']._serialized_end=555
  _globals['_TAGLISTRESPONSE']._serialized_start=557
  _globals['_TAGLISTRESPONSE']._serialized_end=655
  _globals['_TAGS']._serialized_start=658
  _globals['_TAGS']._serialized_end=853
# @@protoc_insertion_point(module_scope)
