services:
  db:
    image: postgres:17 
    container_name: db
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ${DATABASE_NAME}
        POSTGRES_USER: ${DATABASE_USERNAME}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_PORT: ${DATABASE_PORT}
    env_file: .env
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
      - ${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
    env_file: .env
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file: .env
    logging:
      driver: none
  chat-service:
    build:
        context: .
        dockerfile: backend/chat/Dockerfile
    container_name: chat-service
    ports:
      - ${CHAT_PORT}:${CHAT_PORT}
    depends_on:
      - db
      - redis
    env_file: .env

  community-service:
    build:
        context: .
        dockerfile: backend/community/Dockerfile
    container_name: community-service
    ports:
      - ${COMMUNITY_PORT}:${COMMUNITY_PORT}
    depends_on:
      - db
      - redis
    env_file: .env
  django-backend:
    build:
        context: .
        dockerfile: backend/core/Dockerfile
    container_name: django-backend
    ports:
      - ${DJANGO_PORT}:8000
    depends_on:
      - db
      - minio
      - redis
      - auth-service
      - chat-service
      - community-service
    env_file: .env
  svelte-frontend:
    build:
      context: ./frontend
    container_name: svelte-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - django-backend
    working_dir: /app
  auth-service:
    build:
        context: .
        dockerfile: backend/auth/Dockerfile
    container_name: auth-service
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    depends_on:
      - db
      - redis
    env_file: .env
volumes:
  postgres_data:
  minio_data: